### ISSUE TITLE
Minimizing JPEG images in place results in corrupted/0kB files

### ISSUE THREAD

**Issue by bramus** [antonreshetov/image-optimizer#12]
If you have Image Optimizer configured to not use a `.min` suffix nor to use a `minified` folder — i.e. to do an in-place optimization — it will yield 0kB JPEG files.

<img width="662" alt="Screenshot 2022-01-15 at 23 52 56" src="https://user-images.githubusercontent.com/213073/149640171-4cee89f1-de47-4560-9575-be83c9bf150d.png">

_(PNG images it works fine)_

The source image is not the culprit here, as when configuring Image Optimizer to use a `.min` suffix it works fine:

<img width="662" alt="Screenshot 2022-01-15 at 23 53 21" src="https://user-images.githubusercontent.com/213073/149640196-0ae089b5-c75d-45a4-baae-72d17b8e3007.png">

**Comment by antonreshetov** [comment]
Closed because it was fixed in #13
