### ISSUE TITLE
[Feature Request] Reduce dithering at highest quality settings

### ISSUE THREAD

**Issue by Christopher-Hayes** [antonreshetov/image-optimizer#22]
Even with 95-100 quality settings I'm seeing obvious dithering artifacts on the images. I was looking to optimize them a little bit, but the current settings are too aggressive even with the quality turned up.

Before:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/6013871/170381148-61dc1ca1-53b5-432f-a781-90b92ded884c.png">

After:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/6013871/170381166-194b22fa-92e5-45da-8d34-e15862430b71.png">

**Comment by Christopher-Hayes** [comment]
This is probably just a limit with the underlying image conversion. pngquant has the same issue with all the quality settings turned up.

**Comment by antonreshetov** [comment]
Hi @Christopher-Hayes

From the title and description is not explicit, but as I understand it is about `.png`?

Then try adding the option `--floyd` here https://github.com/antonreshetov/image-optimizer/blob/master/src/main/image-compressor.ts#L153

Read more about the settings at https://github.com/kornelski/pngquant

If this works, you can do a PR on adding this setting to the application. Or I'll do it myself, but later.

**Comment by Christopher-Hayes** [comment]
Hi @antonreshetov, yeah sorry it's for PNG. I actually did later resort to pngquant and I had the same issue. `--floyd` did remove the dithering, but it looks a lot worse with dithering off. 

The end result is pngquant compresses to ~30% of the original size at the highest quality setting. (Using `-quality=100 -speed=1`). So, it looks to be a limitation with compressing pings. AFAIK pngquant is the best PNG compression library out there. So this is likely something that can't be fixed.

Google's cwebp (PNG -> WebP) command has a ton of options (like choosing a target file size) that I wish pngquant had. So, I guess I've been a little spoiled with it.
